version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: frozono_db
      POSTGRES_HOST: frozonoapi
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
